//FOR MOCKS
/*
export type Client = {
  id: string;
  name: string;
  profileimg: string;
  balance: number;
  completed_orders: number;
  active_orders: number;
  cancelled_orders: number;
  messages: number;
  children: number;
  reviews: number;
  addresses: number;
  badges: number;
  profile_completion: number;
};
*/

import { ChatType } from "./Chats";
import { ReviewType } from "./Reviews";

export type ProviderPriceCalculationMethod = "DYNAMIC" | "CUSTOM";

export type CompensationRequestStatus =
  | "REQUESTED"
  | "CONTACTED"
  | "IN_PROGRESS"
  | "COMPLETED";

export type CompensationRequest = {
  id?: string;
  _id?: string;
  requestId?: string;
  requestedCompensationInfoAt: string;
  status: CompensationRequestStatus;
  comments: string;
  changedAt: string;
};

export type QualityType =
  | "CAN_BABYSIT_AT_HOME"
  | "LT_LANGUAGE"
  | "FIRST_AID"
  | "DRIVER_LICENSE"
  | "CAR"
  | "CAN_SHOP"
  | "CAN_CLEAN"
  | "NON_SMOKER"
  | "CAN_GO_OUTSIDE"
  | "CAN_COOK"
  | "LOVES_PETS"
  | "CAN_SWIM"
  | "PRIMARY_SCHOOL_TEACHER"
  | "SINGING_TEACHER"
  | "DANCE_TEACHER"
  | "GUITAR"
  | "PIANO"
  | "CAT_ALLERGY"
  | "DOG_ALLERGY"
  | "ASTHMA";

export type User = {
  _id: string;
  id: string;
  userId: string;
  email: string;
  firstName: string;
  lastName: string;
  imgUrl: string;
  createdAt: string;
  updatedAt: string;
  isSuspendedByAdmin: boolean;
  isBannedByAdmin?: boolean;
  suspensionReason: string;
  userLoginMode: string;
  currentMode?: "CLIENT" | "PROVIDER" | string;
  isEmailAutoGenerated: boolean;
  isOnboardingFinished?: boolean;
  videoUrl?: string;
  appVersion?: string | null;
  platform?: "IOS" | "ANDROID" | null;
  imgUrlRemoveMessage?: string | null;
  imgUrlRemovedAt?: string | null;
  imgUrlRemovedByAdminId?: string | null;
  finalPrice?: number;
  locale?: string;
  requestedCompensationInfoAt?: string | null;
  contactedRegardingCompensationAt?: string | null;
};

export type UserDetails = {
  provider?: {
    id: string;
    userId: string;
    createdAt?: string;
    updatedAt?: string;
    isOnboardingFinished?: boolean;
    intro?: string;
    qualitiesIds?: QualityType[];
    totalEarnings: number;
    videoUrl?: string;
    badgesIds?: string[];
    stripeAccountVerifiedAt?: string;
    stripeAccountId?: string;
    isAvailableStatusChangedAt?: string;
    isAvailableStatus?: boolean;
    languages?: string[];
    baseProviderRate: number;
    finalPrice?: number;
    providerPriceCalculationMethod?: ProviderPriceCalculationMethod;
    isShownManageYourRate?: boolean;
    unavailablePeriods?: {
      endsAt: Date;
      startsAt: Date;
      orderId: string;
    }[];
    criminalRecordStatus?: string;
    criminalRecord?: {
      currentStatus?: string;
      applications?: {
        id: string;
      }[];
      status: string;
      statusAdminNotes: string[];
      code: string;
      verifiedAt: string;
      verifiedType: string;
    };
    kycStatus?: string | null;
    stripeKycStatus?: string | null;
    stripeKycMode?: string | null;
    stripeKycAction?: string | null;
    stripeKycBlockingRequirements?: string[] | null;
    stripeKycFutureRequirements?: string[] | null;
    stripeKycPendingVerificationRequirements?: string[] | null;
    stripeKycCurrentDeadline?: string | null;
    stripeKycFutureDeadline?: string | null;
    stripeKycDisabledReason?: string | null;
    stripeKycLastCheckedAt?: string | null;
    stripeKycFieldDescriptions?: Record<string, string>;
    stripe?: {
      accountId?: string | null;
      onboardingFinished?: boolean | null;
      payoutsEnabled?: boolean | null;
      chargesEnabled?: boolean | null;
      accountVerifiedAt?: string | number | null;
      accountType?: string | null;
      email?: string | null;
      currency?: string | null;
      country?: string | null;
    };
    specialSkills?: {
      firstAid?: {
        documentId?: string;
        status?: string; // e.g. 'PENDING' | 'APPROVED'
        verifiedAt?: string;
        appliedAt?: string;
        verifiedByAdminId?: string;
      };
      teacher?: {
        documentId?: string;
        status?: string;
        verifiedAt?: string;
        appliedAt?: string;
        verifiedByAdminId?: string;
      };
      professionalNanny?: {
        documentId?: string;
        status?: string;
        appliedAt?: string;
        verifiedAt?: string;
        verifiedByAdminId?: string;
      };
      artEducator?: {
        documentId?: string;
        status?: string;
        verifiedAt?: string;
        appliedAt?: string;
        verifiedByAdminId?: string;
      };
      language?: {
        documentId?: string;
        status?: string;
        verifiedAt?: string;
        appliedAt?: string;
        verifiedByAdminId?: string;
      };
      psychologist?: {
        documentId?: string;
        status?: string;
        verifiedAt?: string;
        appliedAt?: string;
        verifiedByAdminId?: string;
      };
      sportsCoach?: {
        documentId?: string;
        status?: string;
        verifiedAt?: string;
        appliedAt?: string;
        verifiedByAdminId?: string;
      };
    };
    trackingStatus?: "CONTINUE" | "STOP_FOR_SESSION";
    trackingMode?: "UNAVAILABLE" | "FOREGROUND_ONLY" | "BACKGROUND";
    trackingReason?:
      | "BACKGROUND_TRACKING_STARTED"
      | "DISCLOSURE_DISMISSED"
      | "BACKGROUND_PERMISSION_DENIED"
      | "FOREGROUND_PERMISSION_DENIED"
      | "BACKGROUND_START_FAILED"
      | "FOREGROUND_APP_CLOSED_OR_NO_SIGNAL";
    trackingUpdatedAt?: string;
    lastTrackingPermissions?: {
      status?: "CONTINUE" | "STOP_FOR_SESSION";
      reason?:
        | "BACKGROUND_TRACKING_STARTED"
        | "DISCLOSURE_DISMISSED"
        | "BACKGROUND_PERMISSION_DENIED"
        | "FOREGROUND_PERMISSION_DENIED"
        | "BACKGROUND_START_FAILED"
        | "FOREGROUND_APP_CLOSED_OR_NO_SIGNAL";
      trackingMode?: "UNAVAILABLE" | "FOREGROUND_ONLY" | "BACKGROUND";
      foregroundPermission?: {
        status?: string;
        canAskAgain?: boolean;
      } | null;
      backgroundPermission?: {
        status?: string;
        canAskAgain?: boolean;
      } | null;
      timestamp?: string;
      orderId?: string;
      sessionId?: string;
      updatedAt?: string;
    };
    lastTrackingLocation?: {
      latitude: number;
      longitude: number;
      accuracy?: number | null;
      timestamp: string;
      updatedAt: string;
    };
  };
  client?: {
    id: string;
    userId: string;
    isOnboardingFinished?: boolean;
    requestedCompensationInfoAt?: string | null;
    contactedRegardingCompensationAt?: string | null;
    compensationRequests?: CompensationRequest[];
    languages: string[];
    badgesIds: string[];
    animals: string[];
    rating: number;
    positiveReviewsCount: number;
    createdAt: string; // ISO date string
    updatedAt: string; // ISO date string
  };
  addresses: {
    id: string;
    latitude: number;
    longitude: number;
    location: {
      type: string;
      coordinates: [number, number];
    };
    publicLocation?: {
      type: string;
      coordinates: [number, number];
    };
    country: string;
    city: string;
    street: string;
    houseNumber: string;
    postalCode: string;
    createdAt: string;
    updatedAt: string;
    isDefault: boolean;
  }[];
  children: {
    id: string;
    gender: string;
    name: string;
    birthDate: string;
    allergiesIds: string[];
    disabilitiesIds: string[];
  }[];
  savedProviders: {
    id: string;
    userId: string;
    operationCountry: string;
    isAvailableStatus: boolean;
    rating: number;
    user: {
      id: string;
      firstName: string;
      lastName: string;
      email: string;
      imgUrl: string;
    };
  }[];
  documents: {
    id: string;
    url: string;
    type: string;
    createdAt: string;
    updatedAt: string;
  }[];
  receivedReviews: ReviewType[];
  givenReviews: ReviewType[];
  orders: {
    countsByStatus: {
      count: number;
      status: string;
    }[];
    lastOrder: {
      id: string;
      startsAt: string;
      endsAt: string;
      status: string;
      totalClientPrice: number | null;
    };
    totals: {
      count: number;
      totalSpend: number;
    };
    length: number;
  };
  defaultAddress: {
    id: string;
    latitude: number;
    longitude: number;
    location: {
      type: string;
      coordinates: [number, number];
    };
    publicLocation?: {
      type: string;
      coordinates: [number, number];
    };
    country: string;
    city: string;
    street: string;
    houseNumber: string;
    postalCode: string;
    createdAt: string;
    updatedAt: string;
    isDefault: boolean;
  };
  chatCount: number;
  user: {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    userLoginMode?: string;
    currentMode?: "CLIENT" | "PROVIDER" | string;
    isEmailAutoGenerated?: boolean;
    isOnboardingFinished?: boolean;
    imgUrl: string;
    isBannedByAdmin?: boolean;
    isEmailVerified: boolean;
    isUserVerified: boolean;
    phoneNumber: string;
    country: string;
    roles: string[];
    createdAt: string;
    pushToken?: string;
    videoUrl?: string;
    appVersion?: string | null;
    platform?: "IOS" | "ANDROID" | null;
    imgUrlRemoveMessage?: string | null;
    imgUrlRemovedAt?: string | null;
    imgUrlRemovedByAdminId?: string | null;
    userAppLanguage?: string;
    isSuspendedByAdmin: boolean;
    suspensionReason: string;
  };
  chats: ChatType[];
};
