import { ReviewType } from "./Reviews";

type DetailedOrderProvider = {
  id: string;
  userId: string;
  activityNumber?: string;
  activityNo?: string;
  badgesIds: string[];
  languages: string[];
  operationCountry?: string;
  currentOperationalRegion?: string;
  isAvailableStatus: boolean;
  rating:
    | {
        generalRating: number;
        punctualityRating: number;
        empathyRating: number;
        communicationRating: number;
        cleanlinessRating: number;
      }
    | null;
  positiveReviewsCount: number;
  defaultAddressId: string;
  user: {
    firstName: string;
    lastName: string;
    imgUrl: string;
    phoneNumber: string;
  };
  address: {
    latitude: number;
    longitude: number;
  };
  acactivityNumber?: string;
};

export type DetailedOrderType = {
  id: string;
  clientId: string;
  clientUserId: string;
  isClientUserVerified: boolean;
  clientLongitude: number;
  clientLatitude: number;
  location: {
    type: "Point";
    coordinates: [number, number];
  };
  startsAt: string;
  endsAt: string;
  clientFirstName: string;
  clientImgUrl: string;
  isClientVerified: boolean;
  addressId: string;
  childrenIds: string[];
  isDropOff: boolean;
  isUrgent: boolean;
  currentSelectedAlergiesIds: string[];
  currentSelectedDisabilitiesIds: string[];
  selectedSpokenLanguageIds: string[];
  selectedPetIds: string[];
  createdAt: string;
  updatedAt: string;
  pendingProviderIds: {
    id: string;
    addedAt: string;
    _id: string;
  }[];
  approvedProviderId: string | null;
  serviceProviderPricePerHour: number;
  finalPricePerHour: number;
  serviceDurationHours: number;
  urgentFee: number;
  totalPrice: number;
  subtotalPrice: number;
  totalProviderPrice: number;
  platformFeePrice: number;
  status: string;
  paymentStatus: string;
  paidAt?: string | null;
  stripeCustomerId?: string | null;
  stripePaymentDescription?: string | null;
  orderPrettyId: string;
  isDirectOrderToProvider: boolean;
  requiredProviderId: string | null;
  providerReviewId: string | null;
  clientReviewId: string | null;
  providerReviewCreatedAt: string | null;
  clientReviewCreatedAt: string | null;
  provider_markedAsServiceInProgressAt: string | null;
  provider_markedAsServiceEndedAt: string | null;
  stripeAccountId: string;
  isConfirmed: boolean;
  __v: number;
  children: {
    _id: string;
    id: string;
    gender: string;
    name: string;
    birthDate: string;
    clientId: string;
    allergiesIds: string[];
    disabilitiesIds: string[];
    __v: number;
  }[];
  address: {
    _id: string;
    id: string;
    latitude: number;
    longitude: number;
    location: {
      type: "Point";
      coordinates: [number, number];
    };
    country: string;
    city: string;
    street: string;
    houseNumber: string;
    postalCode: string;
    userId: string;
    userMode: string;
    createdAt: string;
    updatedAt: string;
    __v: number;
  };
  client: {
    _id: string;
    id: string;
    userId: string;
    languages: string[];
    addressesIds: string[];
    badgesIds: string[];
    childIds: string[];
    animals: string[];
    createdAt: string;
    updatedAt: string;
    savedProviderIds: string[];
    leftReviewIds: string[];
    receivedReviewIds: string[];
    rating: number | null;
    positiveReviewsCount: number;
    __v: number;
    defaultAddressId: string;
  };
  clientUser: {
    id: string;
    firstName: string;
    lastName: string;
    email: string;
    imgUrl: string;
    phoneNumber: string;
  };
  approvedProvider: DetailedOrderProvider | null;
  requiredProvider?: DetailedOrderProvider | null;
  pendingProviders: {
    id: string;
    userId: string;
    firstName: string;
    lastName: string;
    imgUrl: string;
    rating: {
      generalRating: number;
      punctualityRating: number;
      empathyRating: number;
      communicationRating: number;
      cleanlinessRating: number;
    };
    isAvailableStatus: boolean;
    positiveReviewsCount: number;
    defaultAddressId: string;
    operationCountry: string;
    badgesIds: string[];
    languages: string[];
    address: {
      latitude: number;
      longitude: number;
    };
    addedAt: string;
  }[];
  isProviderIgnoredEndNotification?: boolean;
  providerIgnoredEndNotificationResolvedReason?: string;
  isReleasedFundsToProvider: boolean;
  releasedFundsToProviderAt: string | null;
  isOrderCanceledLessThan12hBeforeStart?: boolean;
  isOrderCanceledLessThan2hBeforeStart?: boolean;
  refundedAt?: string | null;
  refundedAmount?: number | null;
  refundedAmountCents?: number | null;
  isCancelFeePaidToProvider?: boolean;
  cancelFeePaidToProviderAt?: string | null;
  cancelFeeAmount?: number | null;
  cancelFeeAmountCents?: number | null;
  isClosedByAdmin?: boolean;
  closedByAdminId?: string | null;
  providerSelectionReminder1SentAt?: string | null;
  providerSelectionReminder2SentAt?: string | null;
  providerSelectionAutoCancelWarnedAt?: string | null;
  unfinishedOrderReminderLastEmailSentAt?: string | null;
  unfinishedOrderReminderEmailCount?: number | null;
  reviews?: ReviewType[];
  invoiceDate?: string;
  orderType?: string | null;
  selectedDays?: string[] | null;
  additionalPayments?: {
    id?: string;
    _id?: string;
    stripe_id?: string | null;
    amount?: number | null;
    amountCents?: number | null;
    totalAmount?: number | null;
    totalAmountCents?: number | null;
    currency?: string | null;
    description?: string | null;
    reason?: string | null;
    note?: string | null;
    status?: string | null;
    paymentStatus?: string | null;
    payment_completed_at?: string | null;
    provider_id?: string | null;
    user_id?: string | null;
    order_id?: string | null;
    failure_code?: string | null;
    failure_message?: string | null;
    paymentKind?: string | null;
    providerAmountCents?: number | null;
    platformFeeCents?: number | null;
    stripeBalanceTransactionId?: string | null;
    stripeFee?: number | null;
    stripeFeeCents?: number | null;
    stripeNet?: number | null;
    stripeNetCents?: number | null;
    createdAt?: string | null;
    paidAt?: string | null;
    payoutStatus?: string | null;
    payoutId?: string | null;
    payoutAmountCents?: number | null;
    paidOutAt?: string | null;
    paidOutByAdminId?: string | null;
    payoutState?: "PENDING" | "PAID" | "NOT_PAYABLE" | string | null;
    invoiceId?: string | null;
    additionalPaymentInvoiceId?: string | null;
    invoiceNo?: string | null;
    invoiceDate?: string | null;
    invoiceSource?: string | null;
    invoices?: {
      id?: string;
      _id?: string;
      ownerRole?: "CLIENT" | "PROVIDER" | string | null;
      kind?: string | null;
      invoiceNo?: string | null;
      invoiceDate?: string | null;
      invoiceSource?: string | null;
      isAdditionalPaymentInvoice?: boolean;
    }[];
  }[];
  additionalPaymentsSummary?: {
    payoutPendingCount?: number | null;
    payoutPaidCount?: number | null;
    payoutBalanceCents?: number | null;
    payoutState?: "NONE" | "PENDING" | "PARTIAL" | "PAID" | string | null;
  } | null;
};
