export enum OrderStatusEnum {
  ORDER_CREATED = "ORDER_CREATED",
  PROVIDER_OFFERED_SERVICE = "PROVIDER_OFFERED_SERVICE",
  PROVIDER_ACCEPTED_DIRECT_OFFER = "PROVIDER_ACCEPTED_DIRECT_OFFER",
  PROVIDER_REJECTED_DIRECT_OFFER = "PROVIDER_REJECTED_DIRECT_OFFER",
  BOTH_APPROVED = "BOTH_APPROVED",
  PROVIDER_MARKED_AS_SERVICE_IN_PROGRESS = "PROVIDER_MARKED_AS_SERVICE_IN_PROGRESS",
  PROVIDER_MARKED_AS_SERVICE_ENDED = "PROVIDER_MARKED_AS_SERVICE_ENDED",
  CLIENT_ORDER_CREATION_IN_PROCESS = "CLIENT_ORDER_CREATION_IN_PROCESS",
  CLIENT_CANCELED_ORDER_CREATION_PROCESS = "CLIENT_CANCELED_ORDER_CREATION_PROCESS",
  CANCELED_NO_OFFERS = "CANCELED_NO_OFFERS",
  CANCELED_NOT_STARTED_IN_TIME = "CANCELED_NOT_STARTED_IN_TIME",
  CANCELED_NOT_CONFIRMED_BY_PROVIDER = "CANCELED_NOT_CONFIRMED_BY_PROVIDER",
  CANCELED_BY_PROVIDER = "CANCELED_BY_PROVIDER",
  CANCELED_BY_CLIENT = "CANCELED_BY_CLIENT",
  CANCELED_NOT_PAID_BY_CLIENT = "CANCELED_NOT_PAID_BY_CLIENT",
  CANCELED_ANOTHER_PROVIDER_SELECTED = "CANCELED_ANOTHER_PROVIDER_SELECTED",
  NOT_STARTED_IN_TIME = "NOT_STARTED_IN_TIME",
}


